export const FETCH_WEATHER_START = "FETCH_WEATHER_START";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_FAIL = "FETCH_WEATHER_FAIL";
export const INPUT_CHANGE = "INPUT_CHANGE";
export const INPUT_SUBMIT = "INPUT_SUBMIT";
